import 'server-only';
import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { S3Client, PutObjectCommand, GetObjectCommand, DeleteObjectCommand } from '@aws-sdk/client-s3';
import { env } from '../env';

export interface Stored {
  data: Buffer;
  contentType: string;
}

/** Private object storage for prescriptions and report PDFs. Nothing here is ever publicly addressable. */
export interface Storage {
  put(key: string, data: Buffer, contentType: string): Promise<void>;
  get(key: string): Promise<Stored | null>;
  delete(key: string): Promise<void>;
}

// Keys are generated by us (prefix/uuid.ext). Refuse anything else so a key can never climb out of the folder.
const SAFE_KEY = /^[a-z]+\/[A-Za-z0-9_-]+\/[A-Za-z0-9_-]+\.(?:jpg|png|webp|pdf)$/;
const assertKey = (k: string) => {
  if (!SAFE_KEY.test(k)) throw new Error('invalid storage key');
};

const EXT_TYPE: Record<string, string> = { jpg: 'image/jpeg', png: 'image/png', webp: 'image/webp', pdf: 'application/pdf' };

class LocalStorage implements Storage {
  private root = path.resolve(env().LOCAL_STORAGE_DIR);
  private file(key: string) {
    assertKey(key);
    return path.join(this.root, key);
  }
  async put(key: string, data: Buffer) {
    const f = this.file(key);
    await mkdir(path.dirname(f), { recursive: true });
    await writeFile(f, data, { mode: 0o600 });
  }
  async get(key: string) {
    try {
      return { data: await readFile(this.file(key)), contentType: EXT_TYPE[key.split('.').pop()!] ?? 'application/octet-stream' };
    } catch (e) {
      if ((e as NodeJS.ErrnoException).code === 'ENOENT') return null;
      throw e;
    }
  }
  async delete(key: string) {
    await rm(this.file(key), { force: true });
  }
}

class S3Storage implements Storage {
  private s3 = new S3Client({
    region: env().S3_REGION,
    endpoint: env().S3_ENDPOINT,
    forcePathStyle: env().S3_FORCE_PATH_STYLE,
    credentials: { accessKeyId: env().S3_ACCESS_KEY_ID!, secretAccessKey: env().S3_SECRET_ACCESS_KEY! },
  });
  private bucket = env().S3_BUCKET!;
  async put(key: string, data: Buffer, contentType: string) {
    assertKey(key);
    // Server-side encryption at rest; the bucket itself must have public access blocked.
    await this.s3.send(new PutObjectCommand({ Bucket: this.bucket, Key: key, Body: data, ContentType: contentType, ServerSideEncryption: 'AES256' }));
  }
  async get(key: string) {
    assertKey(key);
    try {
      const r = await this.s3.send(new GetObjectCommand({ Bucket: this.bucket, Key: key }));
      return { data: Buffer.from(await r.Body!.transformToByteArray()), contentType: r.ContentType ?? EXT_TYPE[key.split('.').pop()!] ?? 'application/octet-stream' };
    } catch (e) {
      if ((e as { name?: string }).name === 'NoSuchKey') return null;
      throw e;
    }
  }
  async delete(key: string) {
    assertKey(key);
    await this.s3.send(new DeleteObjectCommand({ Bucket: this.bucket, Key: key }));
  }
}

let impl: Storage | undefined;
export const storage = (): Storage => (impl ??= env().STORAGE_DRIVER === 's3' ? new S3Storage() : new LocalStorage());
export const _resetStorage = () => { impl = undefined; };
